# Settings pertaining to the RabbitMQ connection
rabbitmq-settings:
  rabbitmq-user: "kryo"
  rabbitmq-pwd : "mnl07xs"
  rabbitmq-host: "localhost"
  rabbitmq-virtual-host: "/"

# The RabbitMQ queue that we observe for replies
reply-queue: "replies-1"

# Settings pertaining to logging
log-settings:
  log-level: debug

# The port that the application is run on
application-port: 6367
