# Settings pertaining to the RabbitMQ connection
rabbitmq-settings:
  rabbitmq-user: "guest"
  rabbitmq-pwd : "guest"
  rabbitmq-host: "localhost"
  rabbitmq-virtual-host: "/"

# Settings pertaining to logging
log-settings:
  log-level: debug

# The port that the application is run on
application-port: 3000
