corpus-directory: /home/kryo/temp/javacorpus/elasticsearch

corpus-language: java

# Settings pertaining to logging
log-settings:
  log-level: debug

# The port that the application is run on
application-port: 3666
