search-language: "java"
search-exchange: "java-cluster-1"
search-question-tag: "java"
search-answer-digits: [1]
search-rabbitmq-settings:
  rabbitmq-user: "guest"
  rabbitmq-pwd: "guest"
  rabbitmq-host: "localhost"
  rabbitmq-virtual-host: "/"
search-postgres-database:
  db-user: "kryo"
  db-pwd: "mnl07xs"
  db-name: "testdb"
  db-port: 5432
  db-host: "localhost"
search-semantic-url: "http://localhost:3666/submit"
